headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "D:\\adams\\Documents\\ay\\v2\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "max-age=31536000"

[[headers]]
for = "/*.js"

[headers.values]
Cache-Control = "max-age=31536000"

[[headers]]
for = "/*.css"

[headers.values]
Cache-Control = "max-age=31536000"

[[headers]]
for = "/*.png"

[headers.values]
Cache-Control = "max-age=31536000"

[[headers]]
for = "/*.jpg"

[headers.values]
Cache-Control = "max-age=31536000"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]